apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-allkey
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh","-c","env"]
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
