apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-singlekey-vol
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["ping","www.baidu.com"]
      volumeMounts:
      - name: cm-volume
        mountPath: /etc/config
  volumes:
    - name: cm-volume
      configMap:
        name: special-config
        items:
        - key: SPECIAL_LEVEL
          path: keys 
  restartPolicy: Never
